<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>UniDesk.HardwareRepair</AssemblyName>
    <RootNamespace>UniDesk.HardwareRepair</RootNamespace>
    <Version>2.2.0</Version>
    <FileVersion>2.2.0.0</FileVersion>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
  </PropertyGroup>

</Project>
